anr/urls.py
from django.urls import re_path
from . import views

app_name = 'clubs_anr'

urlpatterns = [
    re_path(r'', views.anr, name='clubs_anr'),
]

cadence/urls.py
from django.urls import re_path
from . import views

app_name = 'clubs_cadence'

urlpatterns = [
    re_path(r'', views.cadence, name='clubs_cadence'),
]

cultboardiitg/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('all_events/', include('all_events.urls')),
    path('team/', include('team.urls')),
    path('manthan/', include('manthan.urls')),
    path('clubs/xpressions/', include('xpressions.urls')),
    path('home/', include('home.urls')),
    path('clubs/anr/', include('anr.urls')),
    path('clubs/cadence/', include('cadence.urls')),
    path('clubs/debsoc/', include('debsoc.urls')),
    path('clubs/finesse/', include('finesse.urls')),
    path('clubs/litsoc/', include('litsoc.urls')),
    path('clubs/lumiere/', include('lumiere.urls')),
    path('clubs/montage/', include('montage.urls')),
    path('clubs/octaves/', include('octaves.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

debsoc/urls.py
from django.urls import re_path
from . import views

app_name = 'clubs_debsoc'

urlpatterns = [
    re_path(r'', views.debsoc, name='clubs_debsoc'),
]

litsoc/urls.py
from django.urls import re_path
from . import views

app_name = 'clubs_litsoc'

urlpatterns = [
    re_path(r'', views.litsoc, name='clubs_litsoc'),
]

manthan/urls.py
from django.urls import re_path
from . import views

app_name = 'manthan'

urlpatterns = [
    re_path(r'', views.manthan, name='manthan'),
]

team/urls.py
from django.urls import re_path
from . import views

app_name = 'team'


urlpatterns = [
    re_path(r'', views.team, name='team'),
]

manthan/models.py
from django.db import models

class Gallery(models.Model):
    image = models.FileField()

class Links(models.Model):
    calender = models.CharField(max_length=500, blank=True, null=True)
    results = models.CharField(max_length=500, blank=True, null=True)
    rulebook = models.CharField(max_length=500, blank=True, null=True)
    photos = models.CharField(max_length=500, blank=True, null=True)

manthan/views.py
from django.shortcuts import render
from .models import Links, Gallery


def manthan(request):
    images = Gallery.objects.all()
    link = Links.objects.all()
    context = {
        'images': images,
        'link': link,
    }
    return render(request, 'manthan.html', context)

manthan/templates/manthan.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Manthan | Cultural Board IITG</title>
    <link rel="stylesheet" href="{% static 'manthan/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Alfa+Slab+One">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:300,400,600">
    <link rel="stylesheet" href="{% static 'manthan/css/block1r2cwwd.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/@bootstrapstudio/bootstrap-better-nav/dist/bootstrap-better-nav.min.css">
    <link rel="stylesheet" href="{% static 'manthan/css/sectionhero.css' %}">
    <link rel="stylesheet" href="{% static 'manthan/css/Footer-Dark.css' %}">
    <link rel="stylesheet" href="{% static 'manthan/css/sectonmain.css' %}">
    <link rel="stylesheet" href="{% static 'manthan/css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'manthan/css/teamcm.css' %}">
    <link rel="stylesheet" href="{% static 'manthan/css/untitled.css' %}">
    <link rel="stylesheet" href="{% static 'montage/fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="https://unpkg.com/@bootstrapstudio/bootstrap-better-nav/dist/bootstrap-better-nav.min.css">
</head>

<body class="flex-row justify-content-center">
    <section class="d-flex flex-column justify-content-between" data-bs-parallax-bg="true" id="hero">
        <nav class="navbar navbar-light navbar-expand-md">
            <div class="container-fluid"><a class="navbar-brand" data-bs-hover-animate="pulse" href="#"></a><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
                <div
                    class="collapse navbar-collapse" id="navcol-1">
                    <ul class="nav navbar-nav ml-auto">
                        <li class="nav-item" role="presentation"><a class="nav-link active" href="{% url 'home:index' %}">Home</a></li>
                        <li class="nav-item dropdown"><a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#">The Clubs</a>
                            <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation" href="{% url 'clubs_litsoc:clubs_litsoc' %}">LitSoc | Literary Club</a><a class="dropdown-item" role="presentation" href="{% url 'clubs_octaves:clubs_octaves' %}">Octaves | Music Club</a><a class="dropdown-item" role="presentation" href="{% url 'clubs_xpressions:clubs_xpressions' %}">Xpression | Drama Club</a>
                                <a
                                    class="dropdown-item" role="presentation" href="{% url 'clubs_debsoc:clubs_debsoc' %}">DebSoc | Debate Club</a><a class="dropdown-item" role="presentation" href="{% url 'clubs_anr:clubs_anr' %}">Anchorenza and RadioG</a><a class="dropdown-item" role="presentation" href="{% url 'clubs_cadence:clubs_cadence' %}">Cadence | Dance Club</a><a class="dropdown-item" role="presentation" href="{% url 'clubs_montage:clubs_montage' %}">Montage| Photography Club</a><a class="dropdown-item" role="presentation" href="{% url 'clubs_lumiere:clubs_lumiere' %}">Lumiere | Movie Club</a></div>
                        </li>
                        <li class="nav-item dropdown"><a class="dropdown-toggle nav-link" data-toggle="dropdown" aria-expanded="false" href="#">Events</a>
                            <div class="dropdown-menu" role="menu"><a class="dropdown-item" role="presentation" href="#">PAF | Performing Arts Festival</a>
                                <a class="dropdown-item" role="presentation" href="https://www.alcheringa.in/">Alcheringa</a>
                                <a class="dropdown-item" role="presentation" href="{% url 'manthan:manthan' %}">Manthan</a>
                                <a class="dropdown-item" role="presentation" href="{% url 'all_events:events' %}">Club Showcases</a>
                            </div>
                        </li>

                        <li class="nav-item" role="presentation"><a class="nav-link" href="#">Blog</a></li>
                        <li class="nav-item" role="presentation"></li>
                        <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'team:team' %}">The Team</a></li>
                    </ul>
            </div>
            </div>
        </nav>
        <div>
        <video autoplay loop muted style="width: 100%;">
            <source src="../../static/manthan/img/cover-vid.mp4" type="video/mp4">
        </video>
        </div>


    <div style="padding-bottom: 84px;">
        <div class="container">
            <div class="row">
                <div class="col">
                    <h1 class="text-capitalize text-left" id="aboutmanthan" style="margin-top: 100px;margin-left: 45px;">About manthan</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <p id="mntnpara" style="height: 100%;margin-right: 16px;width: 100%;"><br>hbivrnkn &nbsp;jrhhr344 3uu h3 thu hheorhhuhu9 h u r hohg oer oerughuerhgjher hgiuh giuhegiuherghher herh iuiu herghierh ghheirh ehriher giheirh i rhu ererhiuerh guihrgiuherg eur uerh guhr guherouherouerguer hgiu eruergiuh gi hhg
                        iuhgiue hg iuhe giuheiughie hgiueu eriuhgiuhei giue i euehe h ehrhg u iuriu ehger gh her er ru heuhg iue hiu u rou grg rg huergh uoeguhhhfd hdfj hkjdfhkjdf dfgk jdfghkj dfgkjdfkg&nbsp;<br><br></p>
                </div>
                <div class="col-md-6" style="width: 100%;height: 100%;">
                    <div class="carousel slide" data-ride="carousel" id="carousel-1" style="width: 100%;height: 100%;">
                        <div class="carousel-inner" role="listbox">
                            <div class="carousel-item active"><img class="w-100 d-block" src="https://cdn.bootstrapstudio.io/placeholders/1400x800.png" alt="Slide Image"></div>
                            <div class="carousel-item"><img class="w-100 d-block" src="https://cdn.bootstrapstudio.io/placeholders/1400x800.png" alt="Slide Image"></div>
                            <div class="carousel-item"><img class="w-100 d-block" src="https://cdn.bootstrapstudio.io/placeholders/1400x800.png" alt="Slide Image"></div>
                        </div>
                        <div><a class="carousel-control-prev" href="#carousel-1" role="button" data-slide="prev"><span class="carousel-control-prev-icon"></span><span class="sr-only">Previous</span></a><a class="carousel-control-next" href="#carousel-1" role="button"
                                data-slide="next"><span class="carousel-control-next-icon"></span><span class="sr-only">Next</span></a></div>
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-1" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-1" data-slide-to="1"></li>
                            <li data-target="#carousel-1" data-slide-to="2"></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-light navbar-expand-md" style="background-color: #78c7e8;">
        <div class="container-fluid"><button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-2"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-2">
                <ul class="nav navbar-nav mx-auto">
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{{ link.rulebook }}" style="color: rgb(0,0,0);font-family: Montserrat, sans-serif;">RuleBook</a></li>
                </ul>
                <ul class="nav navbar-nav mx-auto">
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{{ link.results }}" style="color: rgb(0,0,0);font-family: Montserrat, sans-serif;">Results</a></li>
                </ul>
                <ul class="nav navbar-nav mx-auto">
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{{ link.calender }}" style="color: rgb(0,0,0);font-family: Montserrat, sans-serif;">Calender</a></li>
                </ul>
                <ul class="nav navbar-nav mx-auto">
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{{ link.photos }}" style="color: rgb(0,0,0);font-family: Montserrat, sans-serif;">Photos</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="footer-dark">
        <div class="col item social"><a href="https://www.facebook.com/iitgCulturals/"><i class="icon ion-social-facebook"></i></a><a href="mailto:cultsec@iitg.ac.in"><i class="icon ion-android-mail"></i></a><a href="https://www.youtube.com/channel/UC_croodKpWk9A0qPhxUBD9w"><i class="icon ion-social-youtube"></i></a></div>
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3></h3>
                        <ul>
                            <li></li>
                            <li></li>
                            <li></li>
                        </ul>
                    </div>
                </div>
                <p class="copyright">Cultural Board, IIT Guwahati © 2019</p>
                <p> Page Maintained by General Secretary Cultural Board<hr></p>
                <p>Project Head: Aditya Kakoti</p>
                <p>Associate Project Head: Abhishekh Tiwari</p>
                <p>Designers: Ayush Kiran and Heramb Kininikar</p>
            </div>
        </footer>
    </div>
    <script src="{% static 'manthan/js/jquery.min.js' %}"></script>
    <script src="{% static 'manthan/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'manthan/js/bs-animation.js' %}"></script>
    <script src="https://unpkg.com/@bootstrapstudio/bootstrap-better-nav/dist/bootstrap-better-nav.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
</body>

</html>